// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.196
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WebEssentials
{
    static class Vsix
    {
        public const string Id = "bb7e2273-9a70-4e5e-b4dd-1f361b6166c0";
        public const string Name = "Web Essentials 2017";
        public const string Description = @"The easiest way to set up Visual Studio for the ultimate web development experience. Requires Visual Studio 2017 Update 3 or newer";
        public const string Language = "en-US";
        public const string Version = "1.5";
        public const string Author = "Mads Kristensen";
        public const string Tags = "extensions, vsix, install";
    }
}
